services:
  
  rfid-syafiiyah:
    container_name: rfid-syafiiyah
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-adiiskandar/rfid-syafiiyah:latest}
    ports:
      - protocol: tcp
        published: ${PORT}
        target: 8080
    networks:
      - bridge
    volumes:
      - type: volume
        source: photo
        target: /app/internal/storage/photo
        read_only: false
    env_file: "app.env"

networks:
  bridge:
    driver: bridge

volumes:
  photo:
    name: photo
    
