services:
  
  rfid-syafiiyah:
    container_name: rfid-syafiiyah
    build:
      context: .
      dockerfile: Dockerfile
    image: adiubaidah/rfid-syafiiyah:latest
    ports:
      - protocol: tcp
        published: ${PORT}
        target: ${PORT}
    networks:
      - bridge
    volumes:
      - type: volume
        source: photo
        target: /app/internal/storage/photo
        read_only: true
    env_file: app.env
    environment:
      - GIN_MODE=${GIN_MODE}

networks:
  bridge:
    driver: bridge

volumes:
  photo:
    name: photo
    
