name: Build and Deploy Docker Container

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (dev, stg, prod)"
        required: true
        default: "dev"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Fetch environment secrets from Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: doppler secrets download --config ${{ github.event.inputs.environment }} --format env --no-file > app.env

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{vars.IMAGE_NAME}}:latest
